### PR TITLE
Add test to reproduce warnings

### PR DESCRIPTION
**Pull request by emmenko**
If I run this, I get warnings

```
$ npm test

> postcss-custom-selectors@2.1.0 test /Users/emmenko/dev/src/postcss-custom-selectors
> tape test

TAP version 13
# @custom-selector
ok 1 should transform heading
ok 2 should transform pseudo
ok 3 should transform multiline
ok 4 should transform some hyphen
ok 5 should transform matches selector
Warning: The selector ':--foo-bar' is undefined in CSS!
Warning: The selector ':--foo-baz' is undefined in CSS!
Warning: The selector ':--foo-bar-baz' is undefined in CSS!
Warning: The selector ':--foo-bar-baz' is undefined in CSS!
ok 6 should transform matches selector
ok 7 should transform local extensions

1..7
# tests 7
# pass  7

# ok
```

This is because of the way the selector is matched

```js
rule.selector.indexOf(prop)
```

So if I have following selectors

```css
@custom-selector :--foo .foo;
@custom-selector :--foo-bar .foo .bar;
@custom-selector :--foo-bar-baz .foo .bar .baz;
```

those are the matching results

```js
> ':--foo'.indexOf(':--foo')
0 // <---- ok
> ':--foo'.indexOf(':--foo-bar')
-1 // <---- ok
> ':--foo'.indexOf(':--foo-bar-baz')
-1 // <---- ok
> ':--foo-bar'.indexOf(':--foo')
0 // <---- WRONG
> ':--foo-bar'.indexOf(':--foo-bar')
0 // <---- ok
> ':--foo-bar'.indexOf(':--foo-bar-baz')
-1 // <---- ok
> ':--foo-bar-baz'.indexOf(':--foo')
0 // <---- WRONG
> ':--foo-bar-baz'.indexOf(':--foo-bar')
0 // <---- WRONG
> ':--foo-bar-baz'.indexOf(':--foo-bar-baz')
0 // <---- ok
```

---
How is this suppose to work? Should I use camelcase selectors instead (e.g.: `foo`, `fooBar`, `fooBarBaz`)? Or the matching should be fixed?

Thanks

### CODE REVIEW

**Comment by yisibl** [comment]
Thank you very much.

**Comment by MoOx** [comment]
@yisibl I don't think this PR was made to be merged as is. Maybe we should do something to fix the matching ?

**Comment by emmenko** [comment]
Yes, fix first then merge :)

so what's your opinion on this?

**Comment by MoOx** [comment]
Looks like a bug that should be fixed.

**Comment by emmenko** [comment]
@MoOx ok, so what's the plan here? Do you guys look into it?

**Comment by MoOx** [comment]
@yisibl is the maintainer of this plugin, but if he is busy I can't take a look at it.

**Comment by emmenko** [comment]
Cool, thanks!

**Comment by yisibl** [comment]
I will fixed it.

**Comment by MoOx** [comment]
:+1:

**Comment by yisibl** [comment]
Fixed: https://github.com/postcss/postcss-custom-selectors/commit/c19ff8ffbf8817abeafde72451670b10e30810b0

**Comment by emmenko** [comment]
Cool! :+1: 

Will this be released soon? - no pressure, just to get an idea when :)

**Comment by yisibl** [comment]
@emmenko Has been released.

**Comment by emmenko** [comment]
:+1:

**Comment by emmenko** [comment]
@yisibl @MoOx sorry to bother again, but I'm a bit confused now. 
I see [here](https://github.com/postcss/postcss-custom-selectors/blob/master/test/index.js#L41) that a warning is still generated.

So maybe let me do a step back and ask you something. 
If I have those 2 selectors

```css
@custom-selector :--foo h1;
@custom-selector :--foo-bar-baz h4 h5 h6;

:--foo { color: red; }
:--foo-bar-baz { color: blue; }
```

There is a warning saying `'The selector \':--foo-bar-baz\' is undefined'`.

Why is that? Is it actually wrong to have those kind of selectors? The output is actually ok at the end...

**Comment by MoOx** [comment]
I guess it's another bug. I tried to fix it but it seems I didn't change enough code :/

**Comment by emmenko** [comment]
Hmm, well the test is lying then
https://github.com/postcss/postcss-custom-selectors/blob/master/test/index.js#L41

It should be `... === 0`, or ?

**Comment by MoOx** [comment]
or what ?
If you feel that you can fix the bug, please make a PR :+1:

**Comment by emmenko** [comment]
I'm just saying, what should be the correct behaviour? Is this the correct way to define selectors or is the warning incorrect?

I can make a PR, but I want to know first what should be the expected result...

**Comment by MoOx** [comment]
The warning does not make sense in this case, especially if, as you said, the output is "as expected".

**Comment by emmenko** [comment]
Ok, I will make a PR

**Comment by emmenko** [comment]
@MoOx btw, can you tell me what's wrong here? Is it related to this "bug"?

screen shot 2015-07-01 at 11 56 20

**Comment by MoOx** [comment]
I have to admit that I didn't write this plugin, so I have no idea what is the fuck here :/

**Comment by emmenko** [comment]
Ok. I will try to reproduce / fix it in the PR.

**Comment by MoOx** [comment]
awesome, thanks !

**Pull request merged**
